---
- hosts: all
  become: True
  tasks:
    - name: install apache server
      yum: 
        name: httpd
        state: present
    - name: enable apache on reboot
      ansible.builtin.service:
        name: httpd
        enabled: True
    - name: install git
      yum:
        name: git
        state: present
    - name: deyloy website from git
      ansible.builtin.git:
        repo: https://github.com/thangSu/web-yen.git
        dest: /var/www/html/
    - name: restart apache server
      ansible.builtin.service:
        name: httpd
        state: restarted
