---
- hosts: all
  become: True
  tasks:
    - name: install apache server
      yum: 
        name: httpd
        state: present
    - name: enable apache on reboot
      ansible.builtin.service:
        name: httpd
        enabled: True
    - name: install git
      yum:
        name: git
        state: present
    - name: deloy static web
      ansible.builtin.copy:
        src: /media/thang/Windows-SSD/Users/thangpham/Dropbox/PC/Desktop/Learn/ansible/demo-jenkin-ansible/index.html
        dest: /var/www/html/
    - name: restart apache server
      ansible.builtin.service:
        name: httpd
        state: restarted
